name: "Deploy techdocs"
description: "Deploy your techdocs to an s3 bucket"
inputs:
  entity:
    description: 'documentation entity name'
    required: true
  check:
    description: 'generate the docs but do not publish the site'
    default: 'false'
  TECHDOCS_S3_BUCKET_NAME:
    description: 'techdocs s3 bucket'
    required: true
  AWS_TECHDOCS_ACCESS_KEY_ID:
    description: 'aws access key id'
    required: true
  AWS_TECHDOCS_SECRET_ACCESS_KEY:
    description: 'aws secret access key id'
    required: true
  AWS_TECHDOCS_REGION:
    description: 'aws region'
    required: true
  working-directory:
    description: Working directory of where to run the command.
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v3

    - name: Install techdocs-cli
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
      run: npm install -g @techdocs/cli@0.8.7

    - name: Install mkdocs and mkdocs plugins
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
      run: python -m pip install mkdocs-techdocs-core==0.*

    - name: Generate docs site
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
      run: techdocs-cli generate --no-docker --verbose

    - name: Publish docs site
      if: inputs.check != 'true'
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
      run: |
        techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
      env:
        TECHDOCS_S3_BUCKET_NAME: ${{ inputs.TECHDOCS_S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_TECHDOCS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_TECHDOCS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ inputs.AWS_TECHDOCS_REGION }}
        ENTITY_NAMESPACE: 'default'
        ENTITY_KIND: 'component'
        ENTITY_NAME: ${{ inputs.entity }}
